apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-uma
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: ingress-uma
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
spec:
  replicas: {{ .Values.ingressUma.replicaCount }}
  selector:
    matchLabels:
      {{- include "aggregator.labels" $ | nindent 6 }}
      app.kubernetes.io/component: ingress-uma
  template:
    metadata:
      labels:
        {{- include "aggregator.labels" $ | nindent 8 }}
        app.kubernetes.io/component: ingress-uma
      annotations:
        {{- include "aggregator.annotations" $ | nindent 8 }}
    spec:
      containers:
        - name: ingress-uma
          image: "{{ .Values.ingressUma.image.repository }}:{{ .Values.ingressUma.image.tag }}"
          imagePullPolicy: {{ .Values.ingressUma.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: {{ .Values.ingressUma.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ingressUma.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ingressUma.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.ingressUma.readinessProbe.failureThreshold }}
          env:
            - name: EXTERNAL_HOST
              value: "{{ .Values.external.host }}"
            - name: DISABLE_AUTH
              value: "{{ .Values.ingressUma.disableAuth }}"
      terminationGracePeriodSeconds: {{ .Values.ingressUma.terminationGracePeriodSeconds }}
