apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: server
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "aggregator.labels" $ | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "aggregator.labels" $ | nindent 8 }}
        app.kubernetes.io/component: server
      annotations:
        {{- include "aggregator.annotations" $ | nindent 8 }}
    spec:
      serviceAccountName: aggregator-server-sa
      containers:
        - name: aggregator-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: server-config
            - configMapRef:
                name: spec-config
          {{- if or .Values.auth.oidc.clientSecret .Values.auth.client_credentials.clientSecret }}
          volumeMounts:
            - name: client-secrets
              mountPath: /etc/secrets
              readOnly: true
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
      {{- if or .Values.auth.oidc.clientSecret .Values.auth.client_credentials.clientSecret }}
      volumes:
        - name: client-secrets
          secret:
            secretName: aggregator-server-secret
      {{- end }}
