{{- if or .Values.auth.oidc.clientSecret .Values.auth.client_credentials.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: aggregator-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.oidc.clientSecret }}
  oidcSecret: {{ .Values.auth.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.auth.client_credentials.clientSecret }}
  credSecret: {{ .Values.auth.client_credentials.clientSecret | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.tls.enabled (eq .Values.tls.mode "manual") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{ .Values.tls.certificate.crt | nindent 4 }}
  tls.key: |
    {{ .Values.tls.certificate.key | nindent 4 }}
---
{{- end }}
{{- if and .Values.tls.enabled (eq .Values.tls.mode "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.certManager.issuerName }}
    kind: {{ .Values.tls.certManager.issuerKind }}
    group: {{ .Values.tls.certManager.issuerGroup }}
  dnsNames:
    {{- toYaml .Values.tls.certManager.dnsNames | nindent 4 }}
  {{- with .Values.tls.certManager.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.tls.certManager.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
---
{{- end }}