apiVersion: v1
kind: Service
metadata:
  name: aggregator-server-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aggregator-server
    app.kubernetes.io/component: server
  ports:
    - name: public
      port: {{ .Values.internal.serverPort }}
      targetPort: {{ .Values.internal.serverPort }}
    - name: internal
      port: {{ .Values.internal.serverInternalPort }}
      targetPort: {{ .Values.internal.serverInternalPort }}
