apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
data:
  NAMESPACE: {{ .Release.Namespace }}
  LOG_LEVEL: {{ .Values.loglevel }}

  EXTERNAL_HOST: {{ .Values.external.host }}
  EXTERNAL_HTTP_PORT: {{ .Values.external.httpPort | quote }}
  EXTERNAL_HTTPS_PORT: {{ .Values.external.httpsPort | quote }}

  ALLOWED_REGISTRATION_TYPES: {{ join "," .Values.auth.allowedRegistrationTypes | quote }}
  SOLID_OIDC: {{ .Values.auth.solidOidc | quote }}
  OIDC_CLIENT_ID: {{ .Values.auth.oidc.clientId }}
  OIDC_SERVER: {{ .Values.auth.oidc.server }}

  PROVISION_CLIENT_ID: {{ .Values.auth.provision.clientId }}
  PROVISION_CLIENT_SECRET: {{ .Values.auth.provision.clientSecret }}
  PROVISION_WEBID: {{ .Values.auth.provision.webId }}
  PROVISION_AUTHORIZATION_SERVER: {{ .Values.auth.provision.authServer }}

  CLIENT_CRED_ID: {{ .Values.auth.client_credentials.clientId }}

  INGRESS_CLASS_NAME: {{ .Values.ingressClassName }}
  {{- if .Values.tls.enabled }}
  TLS_SECRET: {{ .Values.tls.secretName }}
  {{- end }}