apiVersion: v1
kind: ConfigMap
metadata:
  name: spec-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
data:
  DEPLOYMENT_CATALOG: {{ .Values.spec.deployment_catalog | quote }}
  SERVICE_COLLECTION: {{ .Values.spec.service_collection | quote }}
  REGISTRATION: {{ .Values.spec.registration | quote }}
