# templates/token-service-rbac.yaml
{{- $namespace := .Release.Namespace }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-service-sa
  namespace: {{ $namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-service-role
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-service-binding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: token-service-sa
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: token-service-role
  apiGroup: rbac.authorization.k8s.io
