serviceConfigurations:
  fetch:
    inputMapping:
      ":url":
        id: URL
    
    outputMapping:
      ":content":
        dataset:
          title: "Fetched Content"
        distribution:
          access:
            urlType: accessURL
            servicePort: 8080
            externalPath: /content
            protocol: http
    
    serviceMapping:
      dataservice:
        title: "Fetch Service"
      
      orchestration:
        type: Deployment
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: fetch
          template:
            metadata:
              labels:
                app: fetch
            spec:
              containers:
                - name: fetch
                  image: fetch
                  env:
                    - name: GET_URL
                      value: "$(URL)"
