host: aggregator.local
auth:
  clientId: aggregator
  server: https://pacsoi-idp.faqir.org/realms/kvasir
  clientSecret: AtctW4sdbmjcfF9gQJIf5RoK6T6wetwG
  allowedRegistrationTypes:
    - none
    - device_code

ingressClassName: aggregator-traefik

transformations:
  - name: get
    spec:
      id: Get
      image: fetch
      fno: |
        @prefix fno: <https://w3id.org/function/ontology#> .
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

        <Get>
          a fno:Function ;
          fno:expects ( <URL> ) ;
          fno:returns ( <Response> ) .

        <URL>
          a fno:Parameter ;
          fno:predicate <url> ;
          fno:type xsd:string ;
          fno:required "true"^^xsd:boolean .

        <Response>
          a fno:Output ;
          fno:predicate <resp> .
      inputMapping:
        url: GET_URL
      outputMapping:
        resp:
          port: 8080
          path: /

loglevel: debug