external:
  host: aggregator.local
  httpPort: 5080
  httpsPort: 5443

auth:
  oidc:
    clientId: aggregator-server
    server: http://localhost:8280/realms/quarkus
    clientSecret: pd3DwvaoxvAcR12SA0s6Q2kv0kxH5vC2
  allowedRegistrationTypes:
    - device_code

ingressClassName: aggregator-traefik

tls:
  enabled: true
  secretName: tls-secret
  mode: selfsigned
  selfSigned:
    crt: aggregator.crt
    key: aggregator.key

transformations:
  - name: kvasir-query
    spec:
      id: KvasirQuery
      image: kvasir-query
      fno: |
        @prefix fno: <https://w3id.org/function/ontology#> .
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

        <KvasirQuery>
          a fno:Function ;
          fno:expects ( <Query> <Sources> <Schema> <Context> ) ;
          fno:returns ( <QueryResult> ) .

        <Query>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <query> ;
          fno:required "true"^^xsd:boolean .
        
        <Sources>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <sources> ;
          fno:required "true"^^xsd:boolean .
        
        <Schema>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <schema> ;
          fno:required "true"^^xsd:boolean .
        
        <Context>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <context> ;
          fno:required "true"^^xsd:boolean .
        
        <QueryResult>
          a fno:Output ;
          fno:predicate <result> .
      inputMapping:
        query: QUERY
        sources: SOURCES
        schema: SCHEMA
        context: CONTEXT
      outputMapping:
        result:
          port: 3000
          path: /

loglevel: debug