host: aggregator.local
auth:
  clientId: aggregator-server
  server: http://localhost:8280/realms/quarkus
  clientSecret: DkkcL2h4YaXELMNEReuSo9I93duKQ0SX
  allowedRegistrationTypes:
    - none
    - device_code

ingressClassName: aggregator-traefik

tls:
  enabled: true
  mode: selfsigned
  selfSigned:
    crt: aggregator.crt
    key: aggregator.key

transformations:
  - name: pacsoi
    spec:
      id: Pacsoi
      image: pacsoi-mock-service
      fno: |
        @prefix fno: <https://w3id.org/function/ontology#> .
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

        <Pacsoi>
          a fno:Function ;
          fno:expects ( ) ;
          fno:returns ( <WeightDistribution> ) .

        <WeightDistribution>
          a fno:Output ;
          fno:predicate <w-distribution> .
      inputMapping: {}
      outputMapping:
        w-distribution:
          port: 8000
          path: /report

loglevel: debug