external:
  host: aggregator.local
  httpPort: 5080
  httpsPort: 5443

auth:
  oidc:
    clientId: aggregator-server
    server: https://pacsoi-idp.faqir.org/realms/kvasir
    clientSecret: 5yUwofhAohc9px5B1ufBvEALJVxygaMu
  allowedRegistrationTypes:
    - device_code

ingressClassName: aggregator-traefik

transformations:
  - name: incremental-kvasir
    spec:
      id: IncrementalKvasir
      image: incremunica-kvasir
      fno: |
        @prefix fno: <https://w3id.org/function/ontology#> .
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

        <IncrementalKvasir>
          a fno:Function ;
          fno:expects ( <Query> <Sources> <Schema> <Context> ) ;
          fno:returns ( <QueryResult> ) .

        <Query>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <query> ;
          fno:required "true"^^xsd:boolean .
        
        <Sources>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <sources> ;
          fno:required "true"^^xsd:boolean .
        
        <Schema>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <schema> ;
          fno:required "true"^^xsd:boolean .
        
        <Context>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <context> ;
          fno:required "true"^^xsd:boolean .
        
        <QueryResult>
          a fno:Output ;
          fno:predicate <result> .
      inputMapping:
        query: QUERY
        sources: SOURCES
        schema: SCHEMA
        context: CONTEXT
      outputMapping:
        result:
          port: 3000
          path: /
  - name: pacsoi
    spec:
      id: Pacsoi
      image: pacsoi-service
      fno: |
        @prefix fno: <https://w3id.org/function/ontology#> .
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
        @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

        <Pacsoi>
          a fno:Function ;
          fno:expects ( <Sources> <WeightSlice> <ProcedureSlice> ) ;
          fno:returns ( <WeightDistribution> ) .
        
        <Sources>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <sources> ;
          fno:required "true"^^xsd:boolean .
        
        <WeightSlice>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <weight-slice> ;
          fno:required "true"^^xsd:boolean .
        
        <ProcedureSlice>
          a fno:Parameter ;
          fno:type xsd:string ;
          fno:predicate <procedure-slice> ;
          fno:required "true"^^xsd:boolean .
        
        <WeightDistribution>
          a fno:Output ;
          fno:predicate <w-dist> .
      inputMapping:
        sources: SOURCES
        weight-slice: WEIGHT_SLICE
        procedure-slice: PROCEDURE_SLICE
      outputMapping:
        w-dist:
          port: 3000
          path: /w-dist

loglevel: debug