apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
  namespace: aggregator-app
data:
  LOG_LEVEL: "debug"
  EXTERNAL_HOST: "aggregator.local"
  DISABLE_AUTH: "false"
  CLIENT_ID: "aggregator"
  AUTH_SERVER: "https://pacsoi-idp.faqir.org/"
  CLIENT_SECRET: "AtctW4sdbmjcfF9gQJIf5RoK6T6wetwG"
  ALLOWED_REGISTRATION_TYPES: "authorization_code,client_credentials"
