apiVersion: fno.knows.idlab.ugent.be/v1
kind: Transformation
metadata:
  name: calculate-weight-distribution
  namespace: aggregator-app
spec:
  id: "CalculateWeightDistribution"
  image: "comunica"
  fno: |
    @prefix fno: <https://w3id.org/function/ontology#> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

    <CalculateWeightDistribution>
      a fno:Function ;
      fno:expects ( <Sources> ) .

    <Sources>
      a fno:Parameter ;
      fno:predicate <sources> ;
      fno:type xsd:string ;
      fno:required "true"^^xsd:boolean .

    <WeightDistribution>
      a fno:Output ;
      fno:predicate <weightDistribution> .
  envMapping:
    sources: SOURCES
