loglevel: info

spec:
  service_collection: /services
  transformation_catalog: /transformations

transformations: []

server:
  replicaCount: 1

  image:
    repository: aggregator-server
    tag: latest
    pullPolicy: Never
  
  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

ingressUma:
  replicaCount: 1

  image:
    repository: ingress-uma
    tag: latest
    pullPolicy: Never

  disableAuth: false

  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

tls:
  enabled: false
  secretName: aggregator-tls