apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fnodescriptions.aggregator.example.org
spec:
  group: aggregator.example.org
  scope: Namespaced
  names:
    plural: fnodescriptions
    singular: fnodescription
    kind: FnoDescription
    shortNames:
      - fno
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [type, description]
              properties:

                type:
                  type: string
                  enum: [deployment-function, implementation]
                  description: >
                    Whether this describes an FnO deployment function or an
                    explicitly selectable fno:Implementation.

                description:
                  type: string
                  description: >
                    RDF description of the deployment function or implementation
                    as a Turtle string.
                              
                serviceConfigurationRef:
                    type: object
                    required: [name]
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
