apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: transformations.agg.idlab.ugent.be
spec:
  group: agg.idlab.ugent.be
  scope: Namespaced        
  names:
    plural: transformations
    singular: transformation
    kind: Transformation
    shortNames:
      - tf
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - id
                - image
                - fno
              properties:
                id:
                  type: string
                  description: "Unique identifier without base prefix"

                image:
                  type: string
                  description: "Container image implementing the transformation"

                fno:
                  type: string
                  description: "FnO (Function Ontology) description"

                inputMapping:
                  type: object
                  description: "Mapping from parameter predicates to ENV variable names"
                  additionalProperties:
                    type: string
                
                outputMapping:
                  type: object
                  description: "Mapping from output predicates to port and path"
                  additionalProperties:
                    type: object
                    required:
                      - port
                      - path
                    properties:
                      port:
                        type: integer
                        description: "Port number"
                      path:
                        type: string
                        description: "Path"
