# This can be moved into a helm chart later
apiVersion: v1
kind: Secret
metadata:
  name: aggregator-provision-uma
  namespace: aggregator-app
type: Opaque
stringData:
  provision_uma_client_id: ""
  provision_uma_client_secret: ""
