external:
  host: aggregator.local
  proto: http
  port: 5080

internal:
  serverPort: 5000
  serverInternalPort: 5001
  instancePort: 5000

auth:
  oidc:
    clientId: <client-id>
    server: <server-url>
    clientSecret: <client-secret>
  allowedRegistrationTypes:
    - device_code

ingressClassName: aggregator-traefik

tls:
  enabled: false

loglevel: debug
