external:
  host: aggregator.local
  httpPort: 5080
  httpsPort: 5443

auth:
  oidc:
    clientId: aggregator-server
    server: http://localhost:8280/realms/kvasir
    clientSecret: ULwNrw7pYeq5bcBl9wYGWVi0Eed7uSg2
  allowedRegistrationTypes:
    - device_code

ingressClassName: aggregator-traefik

tls:
  enabled: false

loglevel: debug