apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-server-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
---
# Role + rRoleBinding for instance management
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aggregator-instance-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
rules:
  # Core resources for aggregator workloads
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]

  # Service accounts management
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]

  # Assign roles to the service accounts (namespace-scoped)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aggregator-instance-manager-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: aggregator-server-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: aggregator-instance-manager
  apiGroup: rbac.authorization.k8s.io
---
# Role + RoleBinding for transformations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aggregator-transformation-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
rules:
  - apiGroups: ["agg.idlab.ugent.be"]
    resources: ["transformations"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aggregator-transformation-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: aggregator-server-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: aggregator-transformation-reader
  apiGroup: rbac.authorization.k8s.io
