apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-server-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
---
# ClusterRole + ClusterRoleBinding for namespace management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator-instance-manager
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces","pods","services","configmaps","serviceaccounts"]
    verbs: ["get","list","create","delete","update","patch","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","create","delete","update","patch","watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list","create","delete","watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","list","watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles","rolebindings"]
    verbs: ["get","list","create","update","delete","watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    resourceNames: ["admin"]
    verbs: ["bind"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregator-instance-manager-binding
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: aggregator-server-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: aggregator-instance-manager
  apiGroup: rbac.authorization.k8s.io
---
# Role + RoleBinding for transformations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aggregator-transformation-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
rules:
  - apiGroups: ["fno.knows.idlab.ugent.be"]
    resources: ["transformations"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aggregator-transformation-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: aggregator-server-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: aggregator-transformation-reader
  apiGroup: rbac.authorization.k8s.io
