{{- if .Values.auth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: aggregator-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.auth.clientSecret | quote }}
---
{{- end }}
