{{- range .Values.transformations }}
apiVersion: fno.knows.idlab.ugent.be/v1
kind: Transformation
metadata:
  name: {{ .name | required "Transformation name is required" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aggregator.labels" $ | nindent 4 }}
  annotations:
    {{- include "aggregator.annotations" $ | nindent 4 }}
spec:
{{ toYaml .spec | indent 2 }}
---
{{- end }}

