fnoDescriptions:
  fetch:
    type: deployment-function
    serviceConfigurationRef:
      name: fetch
    description: |
      @prefix fno: <https://w3id.org/function/ontology#> .
      @prefix aggr: <https://w3id.org/aggregator#> .
      @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

      <Fetch>
        a fno:Function ;
        fno:expects ( <URL> ) ;
        fno:returns ( <DeployedService> ) .

      <URL>
        a fno:Parameter ;
        fno:type xsd:string ;
        fno:predicate <url> ;
        fno:required "true"^^xsd:boolean .

      <DeployedService>
        a fno:Output ;
        fno:predicate <service> ;
        fno:type aggr:Service .
