loglevel: info

auth:
  oidc: {}
  client_credentials: {}
  provision: {}

spec:
  service_collection: /services
  deployment_catalog: /deployments
  registration: /registration

profiles: {}
deploymentFunctions: {}

server:
  replicaCount: 1

  image:
    repository: aggregator-server
    tag: latest
    pullPolicy: Never
  
  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

ingressUma:
  replicaCount: 1

  image:
    repository: ingress-uma
    tag: latest
    pullPolicy: Never

  disableAuth: false

  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  
  terminationGracePeriodSeconds: 50

tokenService:
  replicaCount: 1

  image:
    repository: token-service
    tag: latest
    pullPolicy: Never

  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  
  terminationGracePeriodSeconds: 60

aggregator:
  image:
    repository: aggregator
    tag: latest
    pullPolicy: Never

egressUma:
  image:
    repository: egress-uma
    tag: latest
    pullPolicy: Never

tls:
  enabled: false

ingressClassName: ""
